In [1]:
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

# pandas -> data manipulation
import pandas as pd

# statsbombpy -> access StatsBomb Open Data
from statsbombpy import sb

In [2]:
# ============================================================
# 2. LOAD ALL AVAILABLE COMPETITIONS
# ============================================================

# Load all competitions available in StatsBomb Open Data
competitions = sb.competitions()

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [3]:
# ============================================================
# 3. PREVIEW COMPETITIONS
# ============================================================

# Show first rows
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [4]:
# ============================================================
# 4. CHECK AVAILABLE COLUMNS
# ============================================================

# Show all columns
competitions.columns

Index(['competition_id', 'season_id', 'country_name', 'competition_name',
       'competition_gender', 'competition_youth', 'competition_international',
       'season_name', 'match_updated', 'match_updated_360',
       'match_available_360', 'match_available'],
      dtype='object')

In [5]:
# ============================================================
# 5. FILTER TARGET COMPETITIONS + SEASONS
# ============================================================

# Keep only the tournaments and seasons
# relevant for the project

selected_competitions = competitions[
    (
        (competitions['competition_name'] == 'FIFA World Cup') &
        (competitions['season_name'].isin(['2022']))
    )
    |
    (
        (competitions['competition_name'] == 'UEFA Euro') &
        (competitions['season_name'].isin(['2024']))
    )
    |
    (
        (competitions['competition_name'] == 'Copa America') &
        (competitions['season_name'] == '2024')
    )
    |
    (
        (competitions['competition_name'] == 'African Cup of Nations') &
        (competitions['season_name'] == '2023')
    )
]

In [6]:
# ============================================================
# 6. PREVIEW FILTERED COMPETITIONS
# ============================================================

selected_competitions[
    [
        'competition_name',
        'season_name',
        'competition_id',
        'season_id'
    ]
]

          competition_name season_name  competition_id  season_id
2   African Cup of Nations        2023            1267        107
21            Copa America        2024             223        282
30          FIFA World Cup        2022              43        106
73               UEFA Euro        2024              55        282

In [7]:
# ============================================================
# 7. CREATE MATCHES STORAGE
# ============================================================

# Empty list to store matches dataframes
matches_list = []

In [8]:
# ============================================================
# 8. LOAD MATCHES FROM EVERY SELECTED COMPETITION
# ============================================================

for _, row in selected_competitions.iterrows():

    # Get competition and season IDs
    competition_id = row['competition_id']
    season_id = row['season_id']

    # Load matches from StatsBomb
    matches = sb.matches(
        competition_id=competition_id,
        season_id=season_id
    )

    # Add tournament information to each match
    matches['competition_name'] = row['competition_name']
    matches['season_name'] = row['season_name']

    # Store matches dataframe
    matches_list.append(matches)

    # Print progress
    print(f"Loaded: {row['competition_name']} - {row['season_name']}")

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Loaded: African Cup of Nations - 2023
Loaded: Copa America - 2024

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Loaded: FIFA World Cup - 2022

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Loaded: UEFA Euro - 2024

In [9]:
# ============================================================
# 9. MERGE ALL MATCHES INTO ONE DATAFRAME
# ============================================================

matches_df = pd.concat(
    matches_list,
    ignore_index=True
)

In [10]:
# ============================================================
# 10. CHECK MATCHES DATABASE SIZE
# ============================================================

print(matches_df.shape)

(199, 24)

In [11]:
# ============================================================
# 11. CHECK AVAILABLE MATCH COLUMNS
# ============================================================

matches_df.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'match_week',
       'competition_stage', 'stadium', 'referee', 'home_managers',
       'away_managers', 'data_version', 'shot_fidelity_version',
       'xy_fidelity_version', 'competition_name', 'season_name'],
      dtype='object')

In [12]:
# ============================================================

# 12. PREVIEW MATCHES DATABASE

# ============================================================

matches_df.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version,competition_name,season_name
0,3922240,2024-01-28,20:00:00.000,Africa - African Cup of Nations,2023,Egypt,Congo DR,1,1,available,...,Round of 16,Stade Laurent Pokou,Abongile Tom,Rui Carlos Pinho da Vitória,Sébastien Desabre,1.1.0,2,2,African Cup of Nations,2023
1,3920399,2024-01-19,14:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Mozambique,3,0,available,...,Group Stage,Stade Félix Houphouët-Boigny,Samir Guezzaz,Pedro Leitão Brito,Francisco Queriol Conde Júnior,1.1.0,2,2,African Cup of Nations,2023
2,3920413,2024-01-23,17:00:00.000,Africa - African Cup of Nations,2023,Gambia,Cameroon,2,3,available,...,Group Stage,Stade de Bouaké,Bamlak Tessema Weyesa,Tom Saintfiet,Rigobert Song Bahanag,1.1.0,2,2,African Cup of Nations,2023
3,3920400,2024-01-19,17:00:00.000,Africa - African Cup of Nations,2023,Senegal,Cameroon,3,1,available,...,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Mahmood Ali Mahmood Ismail,Aliou Cissé,Rigobert Song Bahanag,1.1.0,2,2,African Cup of Nations,2023
4,3920409,2024-01-22,17:00:00.000,Africa - African Cup of Nations,2023,Guinea-Bissau,Nigeria,0,1,available,...,Group Stage,Stade Félix Houphouët-Boigny,Bouchra Karboubi,Baciro Candé,José Vítor dos Santos Peseiro,1.1.0,2,2,African Cup of Nations,2023

In [13]:
# ============================================================
# 13. KEEP IMPORTANT COLUMNS
# ============================================================

matches_df = matches_df[
    [
        'match_id',
        'match_date',
        'kick_off',

        'competition_name',
        'season_name',
        'competition_stage',

        'home_team',
        'away_team',
        'home_score',
        'away_score',

        'stadium',

        'referee'
    ]
]

# Preview selected columns
matches_df.head()

,match_id,match_date,kick_off,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score,stadium,referee
0,3922240,2024-01-28,20:00:00.000,African Cup of Nations,2023,Round of 16,Egypt,Congo DR,1,1,Stade Laurent Pokou,Abongile Tom
1,3920399,2024-01-19,14:00:00.000,African Cup of Nations,2023,Group Stage,Cape Verde Islands,Mozambique,3,0,Stade Félix Houphouët-Boigny,Samir Guezzaz
2,3920413,2024-01-23,17:00:00.000,African Cup of Nations,2023,Group Stage,Gambia,Cameroon,2,3,Stade de Bouaké,Bamlak Tessema Weyesa
3,3920400,2024-01-19,17:00:00.000,African Cup of Nations,2023,Group Stage,Senegal,Cameroon,3,1,Stade Charles Konan Banny de Yamoussoukro,Mahmood Ali Mahmood Ismail
4,3920409,2024-01-22,17:00:00.000,African Cup of Nations,2023,Group Stage,Guinea-Bissau,Nigeria,0,1,Stade Félix Houphouët-Boigny,Bouchra Karboubi

In [14]:
# ============================================================
# 14. CREATE TARGET NATIONAL TEAMS LIST
# ============================================================

# List of national teams that will be used as the project universe
# Names are written in English to match StatsBomb team names

world_cup_teams = [
    'Germany',
    'Colombia',
    'Haiti',
    'Paraguay',

    'Saudi Arabia',
    'South Korea',
    'England',
    'Portugal',

    'Algeria',
    "Côte d'Ivoire",
    'Iraq',
    'Czech Republic',

    'Argentina',
    'Croatia',
    'Iran',
    'Congo DR',

    'Australia',
    'Curaçao',
    'Japan',
    'Senegal',

    'Austria',
    'Ecuador',
    'Jordan',
    'South Africa',

    'Belgium',
    'Egypt',
    'Morocco',
    'Sweden',

    'Bosnia and Herzegovina',
    'Scotland',
    'Mexico',
    'Switzerland',

    'Brazil',
    'Spain',
    'Norway',
    'Tunisia',

    'Cape Verde',
    'United States',
    'New Zealand',
    'Turkey',

    'Canada',
    'France',
    'Netherlands',
    'Uruguay',

    'Qatar',
    'Ghana',
    'Panama',
    'Uzbekistan'
]

In [15]:
# ============================================================
# 15. FILTER MATCHES WITH TARGET NATIONAL TEAMS
# ============================================================

filtered_matches = matches_df[
    (matches_df['home_team'].isin(world_cup_teams)) |
    (matches_df['away_team'].isin(world_cup_teams))
].reset_index(drop=True)

In [16]:
# ============================================================
# 16. PREVIEW FILTERED MATCHES
# ============================================================

filtered_matches.sample(5)

,match_id,match_date,kick_off,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score,stadium,referee
162,3930177,2024-06-23,19:00:00.000,UEFA Euro,2024,Group Stage,Scotland,Hungary,0,1,MHPArena,Facundo Tello Figueroa
147,3942382,2024-07-06,19:00:00.000,UEFA Euro,2024,Quarter-finals,Netherlands,Turkey,2,1,Olympiastadion Berlin,Clément Turpin
17,3922838,2024-02-07,22:00:00.000,African Cup of Nations,2023,Semi-finals,Côte d'Ivoire,Congo DR,1,0,Stade Olympique Alassane Ouattara,Ibrahim Mutaz
55,3942415,2024-07-07,01:00:00.000,Copa America,2024,Quarter-finals,Uruguay,Brazil,0,0,Allegiant Stadium,Darío Herrera
82,3857284,2022-11-23,13:00:00.000,FIFA World Cup,2022,Group Stage,Germany,Japan,1,2,Sheikh Khalifa International Stadium,Ivan Arcides Barton Cisneros

In [17]:
# ============================================================
# 17. TOTAL FILTERED MATCHES
# ============================================================

print(f"Total matches: {len(filtered_matches)}")

Total matches: 171

In [18]:
# ============================================================
# 18. MATCH COUNT BY TEAM
# ============================================================

home_counts = filtered_matches['home_team'].value_counts()
away_counts = filtered_matches['away_team'].value_counts()

team_match_counts = home_counts.add(
    away_counts,
    fill_value=0
).sort_values(ascending=False)

team_match_counts

Argentina            13.0
France               13.0
England              12.0
Morocco              11.0
Spain                11.0
                     ...
Gambia                1.0
Ukraine               1.0
Equatorial Guinea     1.0
Burkina Faso          1.0
Angola                1.0
Name: count, Length: 71, dtype: float64

In [19]:
# ============================================================
# SET FINAL MATCHES BASE
# ============================================================

matches = filtered_matches.copy()

print(matches.shape)
print(matches["competition_name"].value_counts())

(171, 12)
competition_name
FIFA World Cup            63
UEFA Euro                 44
African Cup of Nations    34
Copa America              30
Name: count, dtype: int64

In [20]:
# ============================================================
# CLEAN MATCHES BASE
# ============================================================

matches["match_date"] = pd.to_datetime(matches["match_date"])
matches["season_name"] = matches["season_name"].astype(str)

matches["match_label"] = (
    matches["match_date"].dt.strftime("%Y-%m-%d") + " | " +
    matches["home_team"] + " " +
    matches["home_score"].astype(str) + "-" +
    matches["away_score"].astype(str) + " " +
    matches["away_team"]
)

def get_result(row, side):
    if row["home_score"] == row["away_score"]:
        return "Draw"

    if side == "home":
        return "Win" if row["home_score"] > row["away_score"] else "Loss"

    if side == "away":
        return "Win" if row["away_score"] > row["home_score"] else "Loss"

matches["home_result"] = matches.apply(lambda row: get_result(row, "home"), axis=1)
matches["away_result"] = matches.apply(lambda row: get_result(row, "away"), axis=1)

In [21]:
# ============================================================
# COMPETITION SHORT NAME + TOURNAMENT ID
# ============================================================

competition_mapping = {
    "FIFA World Cup": "World Cup",
    "UEFA Euro": "Euro",
    "Copa America": "Copa América",
    "African Cup of Nations": "AFCON"
}

matches["competition_short"] = matches["competition_name"].map(competition_mapping)

matches["tournament_id"] = (
    matches["competition_short"] + "_" +
    matches["season_name"].astype(str)
)

matches.head()

,match_id,match_date,kick_off,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score,stadium,referee,match_label,home_result,away_result,competition_short,tournament_id
0,3922240,2024-01-28,20:00:00.000,African Cup of Nations,2023,Round of 16,Egypt,Congo DR,1,1,Stade Laurent Pokou,Abongile Tom,2024-01-28 | Egypt 1-1 Congo DR,Draw,Draw,AFCON,AFCON_2023
1,3920400,2024-01-19,17:00:00.000,African Cup of Nations,2023,Group Stage,Senegal,Cameroon,3,1,Stade Charles Konan Banny de Yamoussoukro,Mahmood Ali Mahmood Ismail,2024-01-19 | Senegal 3-1 Cameroon,Win,Loss,AFCON,AFCON_2023
2,3920395,2024-01-17,20:00:00.000,African Cup of Nations,2023,Group Stage,Congo DR,Zambia,1,1,Stade Laurent Pokou,Bamlak Tessema Weyesa,2024-01-17 | Congo DR 1-1 Zambia,Draw,Draw,AFCON,AFCON_2023
3,3920407,2024-01-21,20:00:00.000,African Cup of Nations,2023,Group Stage,South Africa,Namibia,4,0,Stade Amadou Gon Coulibaly,Youcef Gamouh,2024-01-21 | South Africa 4-0 Namibia,Win,Loss,AFCON,AFCON_2023
4,3920412,2024-01-23,17:00:00.000,African Cup of Nations,2023,Group Stage,Guinea,Senegal,0,2,Stade Charles Konan Banny de Yamoussoukro,Pacifique Ndabihawenimana,2024-01-23 | Guinea 0-2 Senegal,Loss,Win,AFCON,AFCON_2023

In [22]:
# ============================================================
# SAVE MATCHES BASE
# ============================================================

matches.to_csv("matches.csv", index=False)

print("matches.csv saved successfully!")
print(matches["competition_name"].value_counts())

matches.csv saved successfully!
competition_name
FIFA World Cup            63
UEFA Euro                 44
African Cup of Nations    34
Copa America              30
Name: count, dtype: int64

In [23]:
matches.sample(5)

,match_id,match_date,kick_off,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score,stadium,referee,match_label,home_result,away_result,competition_short,tournament_id
156,3941020,2024-07-01,19:00:00.000,UEFA Euro,2024,Round of 16,Portugal,Slovenia,0,0,Deutsche Bank Park,Daniele Orsato,2024-07-01 | Portugal 0-0 Slovenia,Draw,Draw,Euro,Euro_2024
91,3869685,2022-12-18,17:00:00.000,FIFA World Cup,2022,Final,Argentina,France,3,3,Lusail Stadium,Szymon Marciniak,2022-12-18 | Argentina 3-3 France,Draw,Draw,World Cup,World Cup_2022
33,3920384,2024-01-13,22:00:00.000,African Cup of Nations,2023,Group Stage,Côte d'Ivoire,Guinea-Bissau,2,0,Stade Olympique Alassane Ouattara,Amin Mohamed Omar,2024-01-13 | Côte d'Ivoire 2-0 Guinea-Bissau,Win,Loss,AFCON,AFCON_2023
65,3857271,2022-11-21,13:00:00.000,FIFA World Cup,2022,Group Stage,England,Iran,6,2,Sheikh Khalifa International Stadium,Raphael Claus,2022-11-21 | England 6-2 Iran,Win,Loss,World Cup,World Cup_2022
56,3939973,2024-06-24,01:00:00.000,Copa America,2024,Group Stage,Uruguay,Panama,3,1,Hard Rock Stadium,Piero Maza Gomez,2024-06-24 | Uruguay 3-1 Panama,Win,Loss,Copa América,Copa América_2024