In [1]:
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
from statsbombpy import sb

In [2]:
# ============================================================
# 2. LOAD MATCHES BASE
# ============================================================

matches = pd.read_csv("matches.csv")

print("Matches:", matches.shape)
matches.head()

Matches: (171, 17)

,match_id,match_date,kick_off,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score,stadium,referee,match_label,home_result,away_result,competition_short,tournament_id
0,3922240,2024-01-28,20:00:00.000,African Cup of Nations,2023,Round of 16,Egypt,Congo DR,1,1,Stade Laurent Pokou,Abongile Tom,2024-01-28 | Egypt 1-1 Congo DR,Draw,Draw,AFCON,AFCON_2023
1,3920400,2024-01-19,17:00:00.000,African Cup of Nations,2023,Group Stage,Senegal,Cameroon,3,1,Stade Charles Konan Banny de Yamoussoukro,Mahmood Ali Mahmood Ismail,2024-01-19 | Senegal 3-1 Cameroon,Win,Loss,AFCON,AFCON_2023
2,3920395,2024-01-17,20:00:00.000,African Cup of Nations,2023,Group Stage,Congo DR,Zambia,1,1,Stade Laurent Pokou,Bamlak Tessema Weyesa,2024-01-17 | Congo DR 1-1 Zambia,Draw,Draw,AFCON,AFCON_2023
3,3920407,2024-01-21,20:00:00.000,African Cup of Nations,2023,Group Stage,South Africa,Namibia,4,0,Stade Amadou Gon Coulibaly,Youcef Gamouh,2024-01-21 | South Africa 4-0 Namibia,Win,Loss,AFCON,AFCON_2023
4,3920412,2024-01-23,17:00:00.000,African Cup of Nations,2023,Group Stage,Guinea,Senegal,0,2,Stade Charles Konan Banny de Yamoussoukro,Pacifique Ndabihawenimana,2024-01-23 | Guinea 0-2 Senegal,Loss,Win,AFCON,AFCON_2023

In [3]:
# ============================================================
# 3. LOAD EVENTS FOR ALL MATCHES
# ============================================================

all_events_list = []

for match_id in matches["match_id"].unique():

    try:

        events = sb.events(match_id=match_id)

        events["match_id"] = match_id

        match_info = matches[
            matches["match_id"] == match_id
        ].iloc[0]

        events["competition_name"] = match_info["competition_name"]

        events["season_name"] = str(
            match_info["season_name"]
        )

        events["competition_short"] = (
            match_info["competition_short"]
        )

        events["tournament_id"] = (
            match_info["tournament_id"]
        )

        all_events_list.append(events)

        print(f"✓ Loaded events for match {match_id}")

    except Exception as e:

        print(f"✗ Error loading match {match_id}: {e}")

events = pd.concat(
    all_events_list,
    ignore_index=True
)

print("Events:", events.shape)

events.head()

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922240

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920400

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920395

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920407

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920412

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920415

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920404

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920393

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920394

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920402

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920405

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920416

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922658

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920408

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920410

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3923881

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3923880

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922838

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922837

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922242

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922659

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922356

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3922243

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920396

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920385

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920387

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920419

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920418

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920411

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920398

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920391

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920390

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920388

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3920384

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939991

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939982

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939980

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939977

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939975

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939974

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939986

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939971

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939979

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939988

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939990

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939983

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939972

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939978

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939976

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939992

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942416

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3943077

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3943076

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942852

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942785

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942415

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939973

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942229

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942228

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939985

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939984

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939981

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939989

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3939969

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857276

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857271

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857296

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857274

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857255

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857272

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857278

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857277

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857273

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857275

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857261

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857290

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857298

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857285

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857282

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857297

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857294

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857266

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857284

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857254

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857265

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857301

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857268

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857269

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869321

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857292

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857295

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869685

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869684

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857256

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869151

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857257

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857258

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857288

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857267

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857287

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869486

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857260

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857264

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857289

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869254

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869118

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869519

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869354

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869552

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869420

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869220

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869219

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869253

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869152

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3869117

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857270

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857263

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857283

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857286

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857300

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857299

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857293

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857291

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857281

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857280

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857279

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3857262

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930166

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930159

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930163

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930181

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930178

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930160

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938643

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938641

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938642

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938639

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938637

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938644

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3941019

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942227

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930174

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930176

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930169

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942819

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3943043

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942752

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942382

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942349

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930180

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930171

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3942226

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3938645

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930184

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3941022

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3941021

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3941020

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3941018

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3941017

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930179

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3940983

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3940878

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930177

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930173

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930172

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930167

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930168

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930165

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930164

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930175

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded events for match 3930158
Events: (598221, 119)

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,goalkeeper_shot_saved_to_post,shot_saved_to_post,shot_redirect,goalkeeper_shot_saved_off_target,shot_saved_off_target,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_success_in_play,shot_follows_dribble,half_start_late_video_start
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# ============================================================
# 4. CREATE TEAM MATCH STATS
# ============================================================

team_match_stats = (
    events
    .groupby([
        "competition_name",
        "season_name",
        "competition_short",
        "tournament_id",
        "match_id",
        "team"
    ])
    .agg(
        total_events=("type", "count"),

        shots=("type",
                lambda x: (x == "Shot").sum()),

        passes=("type",
                 lambda x: (x == "Pass").sum()),

        carries=("type",
                  lambda x: (x == "Carry").sum()),

        pressures=("type",
                    lambda x: (x == "Pressure").sum()),

        recoveries=("type",
                     lambda x: (x == "Ball Recovery").sum()),

        duels=("type",
                lambda x: (x == "Duel").sum()),

        interceptions=("type",
                         lambda x: (x == "Interception").sum()),

        blocks=("type",
                  lambda x: (x == "Block").sum()),

        clearances=("type",
                      lambda x: (x == "Clearance").sum())
    )
    .reset_index()
)

team_match_stats.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,total_events,shots,passes,carries,pressures,recoveries,duels,interceptions,blocks,clearances
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,1998,10,598,510,103,48,20,9,12,9
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Guinea-Bissau,1450,10,394,301,145,36,26,15,16,17
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920385,Egypt,2025,22,589,497,141,59,25,11,9,12
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920385,Mozambique,1445,6,373,329,140,31,19,11,20,40
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920387,Cape Verde Islands,1511,15,417,320,122,34,24,9,21,17

In [5]:
# ============================================================
# 5. ADD TEAM XG
# ============================================================

team_xg = (
    events[
        events["type"] == "Shot"
    ]
    .groupby([
        "match_id",
        "team"
    ])
    .agg(
        xg=("shot_statsbomb_xg", "sum")
    )
    .reset_index()
)

team_match_stats = team_match_stats.merge(
    team_xg,
    on=[
        "match_id",
        "team"
    ],
    how="left"
)

team_match_stats["xg"] = (
    team_match_stats["xg"]
    .fillna(0)
)

team_match_stats.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,total_events,shots,passes,carries,pressures,recoveries,duels,interceptions,blocks,clearances,xg
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,1998,10,598,510,103,48,20,9,12,9,0.706896
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Guinea-Bissau,1450,10,394,301,145,36,26,15,16,17,0.529615
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920385,Egypt,2025,22,589,497,141,59,25,11,9,12,1.929200
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920385,Mozambique,1445,6,373,329,140,31,19,11,20,40,0.728199
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920387,Cape Verde Islands,1511,15,417,320,122,34,24,9,21,17,2.720214

In [6]:
# ============================================================
# 6. ADD TEAM COMPLETED PASSES
# ============================================================

completed_passes_team = (
    events[
        (events["type"] == "Pass") &
        (events["pass_outcome"].isna())
    ]
    .groupby([
        "match_id",
        "team"
    ])
    .size()
    .reset_index(
        name="completed_passes"
    )
)

team_match_stats = team_match_stats.merge(
    completed_passes_team,
    on=[
        "match_id",
        "team"
    ],
    how="left"
)

team_match_stats["completed_passes"] = (
    team_match_stats["completed_passes"]
    .fillna(0)
    .astype(int)
)

team_match_stats["pass_completion_pct"] = np.where(
    team_match_stats["passes"] > 0,

    (
        team_match_stats["completed_passes"] /
        team_match_stats["passes"] * 100
    ),

    0
)

team_match_stats.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,total_events,shots,passes,carries,pressures,recoveries,duels,interceptions,blocks,clearances,xg,completed_passes,pass_completion_pct
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,1998,10,598,510,103,48,20,9,12,9,0.706896,517,86.454849
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Guinea-Bissau,1450,10,394,301,145,36,26,15,16,17,0.529615,328,83.248731
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920385,Egypt,2025,22,589,497,141,59,25,11,9,12,1.929200,512,86.926995
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920385,Mozambique,1445,6,373,329,140,31,19,11,20,40,0.728199,309,82.841823
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920387,Cape Verde Islands,1511,15,417,320,122,34,24,9,21,17,2.720214,341,81.774580

In [7]:
# ============================================================
# 7. CREATE PLAYER MATCH STATS
# ============================================================

player_match_stats = (
    events[
        events["player"].notna()
    ]
    .groupby([
        "competition_name",
        "season_name",
        "competition_short",
        "tournament_id",
        "match_id",
        "team",
        "player"
    ])
    .agg(
        total_events=("type", "count"),

        shots=("type",
                lambda x: (x == "Shot").sum()),

        passes=("type",
                 lambda x: (x == "Pass").sum()),

        carries=("type",
                  lambda x: (x == "Carry").sum()),

        pressures=("type",
                    lambda x: (x == "Pressure").sum()),

        recoveries=("type",
                     lambda x: (x == "Ball Recovery").sum()),

        duels=("type",
                lambda x: (x == "Duel").sum()),

        interceptions=("type",
                         lambda x: (x == "Interception").sum()),

        blocks=("type",
                  lambda x: (x == "Block").sum()),

        clearances=("type",
                      lambda x: (x == "Clearance").sum())
    )
    .reset_index()
)

player_match_stats.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,player,total_events,shots,passes,carries,pressures,recoveries,duels,interceptions,blocks,clearances
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Franck Yannick Kessié,134,1,39,36,7,3,1,2,0,0
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ghislain Konan,230,0,72,62,12,5,6,2,1,1
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ibrahim Sangaré,210,0,66,47,24,4,2,1,1,0
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Idrissa Doumbia,11,0,4,3,0,1,0,0,0,0
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Jean-Philippe Krasso,83,4,10,18,9,2,1,1,0,0

In [8]:
# ============================================================
# 8. ADD PLAYER XG
# ============================================================

player_xg = (
    events[
        (events["type"] == "Shot") &
        (events["player"].notna())
    ]
    .groupby([
        "match_id",
        "team",
        "player"
    ])
    .agg(
        xg=("shot_statsbomb_xg", "sum")
    )
    .reset_index()
)

player_match_stats = player_match_stats.merge(
    player_xg,
    on=[
        "match_id",
        "team",
        "player"
    ],
    how="left"
)

player_match_stats["xg"] = (
    player_match_stats["xg"]
    .fillna(0)
)

player_match_stats.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,player,total_events,shots,passes,carries,pressures,recoveries,duels,interceptions,blocks,clearances,xg
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Franck Yannick Kessié,134,1,39,36,7,3,1,2,0,0,0.015857
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ghislain Konan,230,0,72,62,12,5,6,2,1,1,0.000000
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ibrahim Sangaré,210,0,66,47,24,4,2,1,1,0,0.000000
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Idrissa Doumbia,11,0,4,3,0,1,0,0,0,0,0.000000
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Jean-Philippe Krasso,83,4,10,18,9,2,1,1,0,0,0.270901

In [9]:
# ============================================================
# 9. ADD PLAYER COMPLETED PASSES
# ============================================================

completed_passes_player = (
    events[
        (events["type"] == "Pass") &
        (events["pass_outcome"].isna()) &
        (events["player"].notna())
    ]
    .groupby([
        "match_id",
        "team",
        "player"
    ])
    .size()
    .reset_index(
        name="completed_passes"
    )
)

player_match_stats = player_match_stats.merge(
    completed_passes_player,
    on=[
        "match_id",
        "team",
        "player"
    ],
    how="left"
)

player_match_stats["completed_passes"] = (
    player_match_stats["completed_passes"]
    .fillna(0)
    .astype(int)
)

player_match_stats["pass_completion_pct"] = np.where(
    player_match_stats["passes"] > 0,

    (
        player_match_stats["completed_passes"] /
        player_match_stats["passes"] * 100
    ),

    0
)

player_match_stats.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,player,total_events,shots,passes,carries,pressures,recoveries,duels,interceptions,blocks,clearances,xg,completed_passes,pass_completion_pct
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Franck Yannick Kessié,134,1,39,36,7,3,1,2,0,0,0.015857,38,97.435897
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ghislain Konan,230,0,72,62,12,5,6,2,1,1,0.000000,59,81.944444
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ibrahim Sangaré,210,0,66,47,24,4,2,1,1,0,0.000000,57,86.363636
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Idrissa Doumbia,11,0,4,3,0,1,0,0,0,0,0.000000,3,75.000000
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Jean-Philippe Krasso,83,4,10,18,9,2,1,1,0,0,0.270901,5,50.000000

In [10]:
# ============================================================
# 10. CREATE PLAYER POSITIONS BASE
# ============================================================

positions_list = []

for match_id in matches["match_id"].unique():

    try:
        lineups = sb.lineups(match_id=match_id)

        match_info = matches[
            matches["match_id"] == match_id
        ].iloc[0]

        for team_name, lineup_df in lineups.items():

            for _, player_row in lineup_df.iterrows():

                player_name = player_row["player_name"]
                jersey_number = player_row.get("jersey_number", np.nan)
                positions_data = player_row.get("positions", [])

                if isinstance(positions_data, list) and len(positions_data) > 0:

                    first_position = positions_data[0]

                    position_name = first_position.get("position", np.nan)
                    position_id = first_position.get("position_id", np.nan)
                    position_from = first_position.get("from", np.nan)
                    position_to = first_position.get("to", np.nan)

                    starter = position_from == "00:00"

                else:

                    position_name = np.nan
                    position_id = np.nan
                    position_from = np.nan
                    position_to = np.nan
                    starter = False

                positions_list.append({
                    "competition_name": match_info["competition_name"],
                    "season_name": str(match_info["season_name"]),
                    "competition_short": match_info["competition_short"],
                    "tournament_id": match_info["tournament_id"],
                    "match_id": match_id,
                    "team": team_name,
                    "player": player_name,
                    "position": position_name,
                    "position_id": position_id,
                    "from": position_from,
                    "to": position_to,
                    "jersey_number": jersey_number,
                    "starter": starter
                })

        print(f"✓ Loaded positions for match {match_id}")

    except Exception as e:

        print(f"✗ Error loading positions for match {match_id}: {e}")

positions = pd.DataFrame(positions_list)

print("Positions:", positions.shape)

positions.head()

/opt/anaconda3/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

✓ Loaded positions for match 3922240
✓ Loaded positions for match 3920400
✓ Loaded positions for match 3920395
✓ Loaded positions for match 3920407
✓ Loaded positions for match 3920412
✓ Loaded positions for match 3920415
✓ Loaded positions for match 3920404
✓ Loaded positions for match 3920393
✓ Loaded positions for match 3920394
✓ Loaded positions for match 3920402
✓ Loaded positions for match 3920405
✓ Loaded positions for match 3920416
✓ Loaded positions for match 3922658
✓ Loaded positions for match 3920408
✓ Loaded positions for match 3920410
✓ Loaded positions for match 3923881
✓ Loaded positions for match 3923880
✓ Loaded positions for match 3922838
✓ Loaded positions for match 3922837
✓ Loaded positions for match 3922242
✓ Loaded positions for match 3922659
✓ Loaded positions for match 3922356
✓ Loaded positions for match 3922243
✓ Loaded positions for match 3920396
✓ Loaded positions for match 3920385
✓ Loaded positions for match 3920387
✓ Loaded positions for match 3920419
✓ Loaded positions for match 3920418
✓ Loaded positions for match 3920411
✓ Loaded positions for match 3920398
✓ Loaded positions for match 3920391
✓ Loaded positions for match 3920390
✓ Loaded positions for match 3920388
✓ Loaded positions for match 3920384
✓ Loaded positions for match 3939991
✓ Loaded positions for match 3939982
✓ Loaded positions for match 3939980
✓ Loaded positions for match 3939977
✓ Loaded positions for match 3939975
✓ Loaded positions for match 3939974
✓ Loaded positions for match 3939986
✓ Loaded positions for match 3939971
✓ Loaded positions for match 3939979
✓ Loaded positions for match 3939988
✓ Loaded positions for match 3939990
✓ Loaded positions for match 3939983
✓ Loaded positions for match 3939972
✓ Loaded positions for match 3939978
✓ Loaded positions for match 3939976
✓ Loaded positions for match 3939992
✓ Loaded positions for match 3942416
✓ Loaded positions for match 3943077
✓ Loaded positions for match 3943076
✓ Loaded positions for match 3942852
✓ Loaded positions for match 3942785
✓ Loaded positions for match 3942415
✓ Loaded positions for match 3939973
✓ Loaded positions for match 3942229
✓ Loaded positions for match 3942228
✓ Loaded positions for match 3939985
✓ Loaded positions for match 3939984
✓ Loaded positions for match 3939981
✓ Loaded positions for match 3939989
✓ Loaded positions for match 3939969
✓ Loaded positions for match 3857276
✓ Loaded positions for match 3857271
✓ Loaded positions for match 3857296
✓ Loaded positions for match 3857274
✓ Loaded positions for match 3857255
✓ Loaded positions for match 3857272
✓ Loaded positions for match 3857278
✓ Loaded positions for match 3857277
✓ Loaded positions for match 3857273
✓ Loaded positions for match 3857275
✓ Loaded positions for match 3857261
✓ Loaded positions for match 3857290
✓ Loaded positions for match 3857298
✓ Loaded positions for match 3857285
✓ Loaded positions for match 3857282
✓ Loaded positions for match 3857297
✓ Loaded positions for match 3857294
✓ Loaded positions for match 3857266
✓ Loaded positions for match 3857284
✓ Loaded positions for match 3857254
✓ Loaded positions for match 3857265
✓ Loaded positions for match 3857301
✓ Loaded positions for match 3857268
✓ Loaded positions for match 3857269
✓ Loaded positions for match 3869321
✓ Loaded positions for match 3857292
✓ Loaded positions for match 3857295
✓ Loaded positions for match 3869685
✓ Loaded positions for match 3869684
✓ Loaded positions for match 3857256
✓ Loaded positions for match 3869151
✓ Loaded positions for match 3857257
✓ Loaded positions for match 3857258
✓ Loaded positions for match 3857288
✓ Loaded positions for match 3857267
✓ Loaded positions for match 3857287
✓ Loaded positions for match 3869486
✓ Loaded positions for match 3857260
✓ Loaded positions for match 3857264
✓ Loaded positions for match 3857289
✓ Loaded positions for match 3869254
✓ Loaded positions for match 3869118
✓ Loaded positions for match 3869519
✓ Loaded positions for match 3869354
✓ Loaded positions for match 3869552
✓ Loaded positions for match 3869420
✓ Loaded positions for match 3869220
✓ Loaded positions for match 3869219
✓ Loaded positions for match 3869253
✓ Loaded positions for match 3869152
✓ Loaded positions for match 3869117
✓ Loaded positions for match 3857270
✓ Loaded positions for match 3857263
✓ Loaded positions for match 3857283
✓ Loaded positions for match 3857286
✓ Loaded positions for match 3857300
✓ Loaded positions for match 3857299
✓ Loaded positions for match 3857293
✓ Loaded positions for match 3857291
✓ Loaded positions for match 3857281
✓ Loaded positions for match 3857280
✓ Loaded positions for match 3857279
✓ Loaded positions for match 3857262
✓ Loaded positions for match 3930166
✓ Loaded positions for match 3930159
✓ Loaded positions for match 3930163
✓ Loaded positions for match 3930181
✓ Loaded positions for match 3930178
✓ Loaded positions for match 3930160
✓ Loaded positions for match 3938643
✓ Loaded positions for match 3938641
✓ Loaded positions for match 3938642
✓ Loaded positions for match 3938639
✓ Loaded positions for match 3938637
✓ Loaded positions for match 3938644
✓ Loaded positions for match 3941019
✓ Loaded positions for match 3942227
✓ Loaded positions for match 3930174
✓ Loaded positions for match 3930176
✓ Loaded positions for match 3930169
✓ Loaded positions for match 3942819
✓ Loaded positions for match 3943043
✓ Loaded positions for match 3942752
✓ Loaded positions for match 3942382
✓ Loaded positions for match 3942349
✓ Loaded positions for match 3930180
✓ Loaded positions for match 3930171
✓ Loaded positions for match 3942226
✓ Loaded positions for match 3938645
✓ Loaded positions for match 3930184
✓ Loaded positions for match 3941022
✓ Loaded positions for match 3941021
✓ Loaded positions for match 3941020
✓ Loaded positions for match 3941018
✓ Loaded positions for match 3941017
✓ Loaded positions for match 3930179
✓ Loaded positions for match 3940983
✓ Loaded positions for match 3940878
✓ Loaded positions for match 3930177
✓ Loaded positions for match 3930173
✓ Loaded positions for match 3930172
✓ Loaded positions for match 3930167
✓ Loaded positions for match 3930168
✓ Loaded positions for match 3930165
✓ Loaded positions for match 3930164
✓ Loaded positions for match 3930175
✓ Loaded positions for match 3930158
Positions: (8492, 13)

,competition_name,season_name,competition_short,tournament_id,match_id,team,player,position,position_id,from,to,jersey_number,starter
0,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Chancel Mbemba Mangulu,Right Center Back,3.0,00:00,None,22,True
1,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Arthur Masuaku,Left Back,6.0,00:00,None,26,True
2,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Samuel Moutoussamy,Left Defensive Midfield,11.0,00:00,None,8,True
3,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Aaron Tshibola,Right Defensive Midfield,9.0,78:13,None,6,False
4,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Joris Kayembe Ditu,NaN,NaN,NaN,NaN,12,False

In [11]:
# ============================================================
# 11. ADD POSITION COORDINATES
# ============================================================

position_coordinates = {
    "Goalkeeper": (8, 40),

    "Left Back": (28, 12),
    "Left Center Back": (25, 28),
    "Center Back": (25, 40),
    "Right Center Back": (25, 52),
    "Right Back": (28, 68),

    "Left Wing Back": (38, 10),
    "Right Wing Back": (38, 70),

    "Left Defensive Midfield": (45, 28),
    "Center Defensive Midfield": (45, 40),
    "Right Defensive Midfield": (45, 52),

    "Left Center Midfield": (60, 28),
    "Center Midfield": (60, 40),
    "Right Center Midfield": (60, 52),

    "Left Midfield": (62, 14),
    "Right Midfield": (62, 66),

    "Left Attacking Midfield": (78, 28),
    "Center Attacking Midfield": (78, 40),
    "Right Attacking Midfield": (78, 52),

    "Left Wing": (88, 12),
    "Right Wing": (88, 68),

    "Left Center Forward": (100, 32),
    "Center Forward": (105, 40),
    "Right Center Forward": (100, 48),

    "Secondary Striker": (92, 40)
}

position_xy = pd.DataFrame([
    {
        "position": position,
        "position_x": coords[0],
        "position_y": coords[1]
    }
    for position, coords in position_coordinates.items()
])

positions = positions.merge(
    position_xy,
    on="position",
    how="left"
)

positions.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,player,position,position_id,from,to,jersey_number,starter,position_x,position_y
0,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Chancel Mbemba Mangulu,Right Center Back,3.0,00:00,None,22,True,25.0,52.0
1,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Arthur Masuaku,Left Back,6.0,00:00,None,26,True,28.0,12.0
2,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Samuel Moutoussamy,Left Defensive Midfield,11.0,00:00,None,8,True,45.0,28.0
3,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Aaron Tshibola,Right Defensive Midfield,9.0,78:13,None,6,False,45.0,52.0
4,African Cup of Nations,2023,AFCON,AFCON_2023,3922240,Congo DR,Joris Kayembe Ditu,NaN,NaN,NaN,NaN,12,False,NaN,NaN

In [12]:
# ============================================================
# 12. CHECK POSITIONS WITHOUT COORDINATES
# ============================================================

positions_without_xy = (
    positions[
        positions["position_x"].isna()
    ]["position"]
    .dropna()
    .unique()
)

positions_without_xy

array([], dtype=object)

In [13]:
# ============================================================
# 13. MERGE PLAYER STATS WITH POSITIONS
# ============================================================

player_match_stats_with_positions = player_match_stats.merge(
    positions[
        [
            "match_id",
            "team",
            "player",
            "position",
            "position_id",
            "position_x",
            "position_y",
            "jersey_number",
            "starter",
            "from",
            "to"
        ]
    ],
    on=["match_id", "team", "player"],
    how="left"
)

player_match_stats_with_positions.head()

,competition_name,season_name,competition_short,tournament_id,match_id,team,player,total_events,shots,passes,...,completed_passes,pass_completion_pct,position,position_id,position_x,position_y,jersey_number,starter,from,to
0,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Franck Yannick Kessié,134,1,39,...,38,97.435897,Right Center Midfield,13.0,60.0,52.0,8,True,00:00,None
1,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ghislain Konan,230,0,72,...,59,81.944444,Left Back,6.0,28.0,12.0,3,True,00:00,None
2,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Ibrahim Sangaré,210,0,66,...,57,86.363636,Center Defensive Midfield,10.0,45.0,40.0,18,True,00:00,89:38
3,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Idrissa Doumbia,11,0,4,...,3,75.000000,Center Defensive Midfield,10.0,45.0,40.0,25,False,89:38,None
4,African Cup of Nations,2023,AFCON,AFCON_2023,3920384,Côte d'Ivoire,Jean-Philippe Krasso,83,4,10,...,5,50.000000,Center Forward,23.0,105.0,40.0,11,True,00:00,60:47

In [29]:
# ============================================================
# 14. SAVE OUTPUTS
# ============================================================

events.to_csv("events.csv", index=False)

team_match_stats.to_csv(
    "team_match_stats.csv",
    index=False
)

player_match_stats.to_csv(
    "player_match_stats.csv",
    index=False
)

positions.to_csv(
    "positions.csv",
    index=False
)

player_match_stats_with_positions.to_csv(
    "player_match_stats_with_positions.csv",
    index=False
)

print("Saved:")
print("events.csv")
print("team_match_stats.csv")
print("player_match_stats.csv")
print("positions.csv")
print("player_match_stats_with_positions.csv")

Saved:
events.csv
team_match_stats.csv
player_match_stats.csv
positions.csv
player_match_stats_with_positions.csv